
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global
[<assembly: Android.Runtime.ResourceDesignerAttribute("IAintEvenAngry.Resource", IsApplication=true)>]
    do ()

namespace IAintEvenAngry
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnException34ce4ed633bd43c5bc5863023f451b9a of obj
    exception ReturnNoneException34ce4ed633bd43c5bc5863023f451b9a
    [<AutoOpen>]
    module FuncConvertFinalOverload34ce4ed633bd43c5bc5863023f451b9a =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")>]
        
        (* partial *)Resource () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            static member UpdateIdValues  () =
                global.OsmSharp.Android.UI.Resource.String.library_name <- Resource_String.library_name


    
    and
        
        (* partial *)Resource_Attribute () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Drawable () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f020000
            static member Icon = 2130837504
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Id () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f050002
            static member buttonLogin = 2131034114
            
            // aapt resource value: 0x7f050001
            static member editTextPassword = 2131034113
            
            // aapt resource value: 0x7f050000
            static member editTextUsername = 2131034112
            
            // aapt resource value: 0x7f050003
            static member textViewInformasi = 2131034115
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Layout () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f030000
            static member Main = 2130903040
            
            // aapt resource value: 0x7f030001
            static member Map = 2130903041
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_String () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f040002
            static member ApplicationName = 2130968578
            
            // aapt resource value: 0x7f040001
            static member Hello = 2130968577
            
            // aapt resource value: 0x7f040000
            static member library_name = 2130968576
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)

